<<<<<<< HEAD
print("          * ")
print("         * *")
print("        * * *")
print("       * * * *")
print("      * * * * *")
print("       * * * *")
print("        * * *")
print("         * *")
=======
print("          * ")
print("         * *")
print("        * * *")
print("       * * * *")
print("      * * * * *")
print("       * * * *")
print("        * * *")
print("         * *")
>>>>>>> 27c6f61dd9d7e30848998e4339f7041be919f0bb
print("          *")